/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nwpu_mylearnndkdemo2_Hello */

#ifndef _Included_com_nwpu_mylearnndkdemo2_Hello
#define _Included_com_nwpu_mylearnndkdemo2_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nwpu_mylearnndkdemo2_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nwpu_mylearnndkdemo2_Hello_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
