/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nwpu_ndkbulidtest_JniUtils */

#ifndef _Included_com_nwpu_ndkbulidtest_JniUtils
#define _Included_com_nwpu_ndkbulidtest_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nwpu_ndkbulidtest_JniUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nwpu_ndkbulidtest_JniUtils_getName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
